import { Slider } from "slider.slint";
import { TopShortcut } from "top-shortcut.slint";
import { ViewerArea } from "viewer-area.slint";
import { InfoArea } from "info-area.slint";
import { InfoState } from "info-state.slint";
export { Logic } from "logic.slint";
export { ViewerState } from "viewer-state.slint";

export component AppWindow inherits Window {
    property <length> initial-width: 1280px;
    property <length> initial-height: 720px;

    in-out property <string> file-list;
    in-out property <float> view-width-ratio: InfoState.info-active ? InfoState.saved-width-ratio : 1.0;

    animate view-width-ratio {
        duration: 300ms;
        easing: ease-in-out;
    }

    preferred-width: initial-width;
    preferred-height: initial-height;

    default-font-size: 16px;

    MenuBar {
        Menu {
            title: "File";
            MenuItem {
                title: "Open image";
                activated => {
                    debug("Open image menu activated");
                }
            }

            MenuItem {
                title: "Open directory";
                activated => {
                    debug("Open directory menu activated");
                }
            }
        }
    }

    l := Rectangle {
        x: 0;
        width: view-width-ratio * parent.width;
        clip: true;

        ViewerArea { }
    }

    slider := Slider {
        x: l.width;
        visible: InfoState.info-active;
        moved(x) => {
            InfoState.saved-width-ratio += (x - (slider.width / 2)) / parent.width;
        }
    }

    Rectangle {
        x: l.width + slider.width;
        width: parent.width - (l.width + slider.width);
        visible: InfoState.info-active;
        clip: true;

        InfoArea { }
    }

    TopShortcut { }
}
