import {
    VerticalBox,
    ScrollView,
    GroupBox,
    TextEdit,
} from "std-widgets.slint";
import { Table } from "table.slint";
import { ViewerState } from "viewer-state.slint";

export component InfoArea inherits ScrollView {
    min-width: 200px;
    VerticalBox {
        alignment: start;

        GroupBox {
            title: @tr("Basic Info");
            content-padding: 1px;

            Table {
                data: [
                    { key: @tr("Filename"), value: "aaa-afewfajewiaofjew-fewafeawfewa-hoge.png" },
                    { key: @tr("Size"), value: "1.2 MB" },
                    { key: @tr("Resolution"), value: "1156 x 864" }
                ];
            }
        }

        GroupBox {
            title: @tr("XMP");
            content-padding: 1px;

            Table {
                data: [
                    {
                        key: "Rating",
                        value: 0 <= ViewerState.current-rating ? ViewerState.current-rating : "None"
                    }
                ];
            }
        }

        GroupBox {
            title: @tr("Positive Prompt");
            content-padding: 1px;

            TextEdit {
                height: 14rem;
                wrap: word-wrap;
                read-only: true;
                text: ViewerState.positive-prompt;
            }
        }

        GroupBox {
            title: @tr("Negative Prompt");
            content-padding: 1px;

            TextEdit {
                height: 2rem;
                wrap: word-wrap;
                read-only: true;
                text: ViewerState.negative-prompt;
            }
        }

        GroupBox {
            title: @tr("Generation Settings");
            content-padding: 1px;

            Table {
                data: ViewerState.sd-parameters;
            }
        }

        GroupBox {
            title: @tr("Status🚧");
            content-padding: 1px;

            Table {
                data: [{ key: "Auto-Reload", value: ViewerState.auto-reload-active ? "Active" : "Inactive" }];
            }
        }

        GroupBox {
            title: @tr("Errors🚧");
            content-padding: 1px;

            TextEdit {
                height: 4rem;
                wrap: word-wrap;
                read-only: true;
                text: ViewerState.error-message;
            }
        }
    }
}
