export global Logic {
    callback copy-image();
    callback next-image();
    callback prev-image();
    callback start-auto-reload();
    callback stop-auto-reload();
    callback rate-0();
    callback rate-1();
    callback rate-2();
    callback rate-3();
    callback rate-4();
    callback rate-5();

    callback select-image();

    callback transition-viewer();
    callback transition-directory();
}
