import { Palette } from "std-widgets.slint";
component TableRow inherits Rectangle {
    in property <string> key;
    in property <string> value;
    in property <int> index;

    property <length> rec-padding: 0.2rem;
    background: mod(index,2) == 0 ? Palette.background.darker(0.1) : Palette.background.brighter(0.1);

    HorizontalLayout {
        padding: rec-padding;
        alignment: space-between;

        VerticalLayout {
            Text {
                horizontal-alignment: left;
                overflow: elide;
                text: key + ":";
            }
        }

        VerticalLayout {
            Text {
                horizontal-alignment: right;
                wrap: char-wrap;
                text: value;
            }
        }
    }
}

export component Table inherits VerticalLayout {
    width: 100%;
    in property <[{key: string, value: string}]> data: [];

    for r[index] in data: TableRow {
        key: r.key;
        value: r.value;
        index: index;
    }
}
