import {
    Palette,
    Button,
    ScrollView,
} from "std-widgets.slint";
import { Logic } from "logic.slint";
import { ViewerState } from "viewer-state.slint";
import { InfoArea } from "info-state.slint";
import { UiButton } from "components/ui-button.slint";

export component ViewerArea inherits VerticalLayout {
    property <bool> image-loaded: ViewerState.image-loaded;

    alignment: center;

    if image-loaded: Rectangle {
        background: Palette.alternate-background;
        height: 100%;

        ContextMenuArea {
            Menu {
                MenuItem {
                    title: @tr("Copy");
                    activated => {
                        debug("Copy");
                    }
                }

                MenuItem {
                    title: @tr("Reset Zoom");
                    activated => {
                        debug("Reset Zoom");
                    }
                }
            }
        }

        Image {
            width: root.width;
            height: root.height;
            image-fit: contain;
            source: ViewerState.dynamic-image;
        }

        Rectangle {
            y: 0;
            width: 100%;
            height: 3rem;
            background: Palette.background.transparentize(0.5);

            Text {
                vertical-alignment: center;
                text: ViewerState.current-index + " / " + ViewerState.total-index;
            }

            HorizontalLayout {
                padding: 0.5rem;
                alignment: space-between;
                UiButton {
                    icon: @image-url("icons/lucide-arrow-big-left.svg");
                    clicked => {
                        debug("Transition to parent directory");
                        Logic.transition-directory();
                    }
                }

                HorizontalLayout {
                    spacing: 0.5rem;
                    UiButton {
                        icon: @image-url("icons/lucide-info.svg");
                        active: InfoArea.info-active;
                        clicked => {
                            debug("Toggle info area");
                            InfoArea.info-active = !InfoArea.info-active;
                        }
                    }

                    UiButton {
                        icon: @image-url("icons/lucide-ellipsis-vertical.svg");
                        clicked => {
                            debug("Open menu");
                        }
                        // TODO: ここにDeleteやCopyを追加
                    }
                }
            }
        }
    }

    if !image-loaded: HorizontalLayout {
        alignment: center;
        Button {
            text: "Open image";
            width: 20rem;
            height: 4rem;
            clicked => {
                Logic.select-image();
            }
        }
    }
}
