import {
    Palette,
    Button,
    ScrollView,
} from "std-widgets.slint";
import { Logic } from "logic.slint";
import { ViewerState } from "viewer-state.slint";
import { InfoState } from "info-state.slint";
import { UiButton } from "components/ui-button.slint";
import { LeftRightNavigation } from "components/left-right-navigation.slint";

export component ViewerArea inherits Rectangle {
    property <bool> image-loaded: ViewerState.image-loaded;
    property <bool> ui-active: ViewerState.ui-active;

    ui-timer := Timer {
        interval: 3s;
        triggered => {
            debug("UI timeout");
            ViewerState.ui-active = false;
            self.stop();
        }
    }

    // Watch for ui-active changes to restart timer
    changed ui-active => {
        if ui-active {
            ui-timer.restart();
        }
    }

    if image-loaded: Rectangle {
        background: Palette.alternate-background;
        clip: true;

        ContextMenuArea {
            Menu {
                MenuItem {
                    title: @tr("Copy");
                    activated => {
                        debug("Copy");
                    }
                }

                MenuItem {
                    title: @tr("Reset Zoom");
                    activated => {
                        debug("Reset Zoom");
                    }
                }
            }
        }

        TouchArea {
            clicked => {
                debug("clicked");
                ViewerState.ui-active = true;
            }
            double-clicked => {
                debug("double-clicked");
            }
            moved => {
                debug(self.mouse-x, self.mouse-y);
            }
        }

        Image {
            width: 100%;
            height: 100%;
            preferred-width: 0;
            preferred-height: 0;
            image-fit: contain;
            source: ViewerState.dynamic-image;
        }

        if ui-active: LeftRightNavigation {
            is-left: true;
            x: 0;
            clicked => {
                debug("left clicked");
                ViewerState.ui-active = true;
            }
        }

        if ui-active: LeftRightNavigation {
            is-left: false;
            x: root.width - 5rem;
            clicked => {
                debug("right clicked");
                ViewerState.ui-active = true;
            }
        }

        if ui-active: Rectangle {
            y: 0;
            height: 3rem;
            background: Palette.background.transparentize(0.3);

            Text {
                vertical-alignment: center;
                text: ViewerState.current-index + " / " + ViewerState.total-index;
            }

            HorizontalLayout {
                padding: 0.5rem;
                alignment: space-between;
                UiButton {
                    icon: @image-url("icons/lucide-arrow-big-left.svg");
                    clicked => {
                        debug("Transition to parent directory");
                        Logic.transition-directory();
                    }
                }

                HorizontalLayout {
                    spacing: 0.5rem;
                    UiButton {
                        icon: @image-url("icons/lucide-info.svg");
                        active: InfoState.info-active;
                        clicked => {
                            debug("Toggle info area");
                            InfoState.info-active = !InfoState.info-active;
                        }
                    }

                    UiButton {
                        icon: @image-url("icons/lucide-ellipsis-vertical.svg");
                        clicked => {
                            debug("Open menu");
                        }
                        // TODO: ここにDeleteやCopyを追加
                    }
                }
            }
        }
    }

    if !image-loaded: Button {
        preferred-width: 20rem;
        preferred-height: 6rem;

        text: "Open image";

        clicked => {
            Logic.select-image();
        }
    }
}
