import {
    Palette,
    Button,
    ScrollView,
} from "std-widgets.slint";
import { Logic } from "logic.slint";
import { ViewState } from "view-state.slint";

export component ViewArea inherits VerticalLayout {
    property <bool> image-loaded: ViewState.image-loaded;

    alignment: center;

    if image-loaded: Rectangle {
        background: Palette.alternate-background;
        clip: true;

        ContextMenuArea {
            Menu {
                MenuItem {
                    title: @tr("Copy");
                    activated => {
                        debug("Copy");
                    }
                }

                MenuItem {
                    title: @tr("Reset Zoom");
                    activated => {
                        debug("Reset Zoom");
                    }
                }
            }
        }

        Image {
            width: root.width;
            height: root.height;
            image-fit: contain;
            source: ViewState.dynamic-image;
        }
    }

    if !image-loaded: HorizontalLayout {
        alignment: center;
        Button {
            text: "Open image";
            width: 20rem;
            height: 4rem;
            clicked => {
                Logic.select-image();
            }
        }
    }
}
