export global ViewState {
    in-out property <image> dynamic-image;
    in-out property <bool> image-loaded: false;
    in-out property <int> current-index: -1;
    in-out property <int> total-index: -1;
    in-out property <string> error-message: "";
    in-out property <bool> rating-in-progress: false;
    in-out property <int> current-rating: -1;
    in-out property <bool> auto-reload-active: false;
    in-out property <string> positive-prompt: "";
    in-out property <string> negative-prompt: "";
    in-out property <[{key: string, value: string}]> sd-parameters: [];
}
